### ISSUE TITLE
unable to start phoenix server

### ISSUE THREAD

**Issue by laurmcarter** [laurmcarter/mechs#1]
Encountering error upon attempting to start the phoenix server:
```
mix phx.server

** (Mix) Could not start application mechs: exited in: Mechs.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, GRPC.Server.Supervisor, {:function_clause, [{GRPC.Server.Supervisor, :init, [[strategy: :one_for_one, name: Mechs.GRPC.Supervisor]], [file: 'lib/grpc/server/supervisor.ex', line: 41]}, {:supervisor, :init, 1, [file: 'supervisor.erl', line: 330]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}}
            (mechs 0.1.0) lib/mechs/application.ex:30: Mechs.Application.start/2
            (kernel 8.5.4) application_master.erl:293: :application_master.start_it_old/4
```

**Comment by laurmcarter** [comment]
```
mix phx.server

** (Mix) Could not start application mechs: Mechs.Application.start(:normal, []) returned an error: shutdown: failed to start child: GRPC.Server.Supervisor
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in GRPC.Server.Supervisor.init/1
            (grpc 0.5.0) lib/grpc/server/supervisor.ex:41: GRPC.Server.Supervisor.init([services: [{Mechs.GreeterService, 50051}], strategy: :one_for_one])
            (stdlib 4.3) supervisor.erl:330: :supervisor.init/1
            (stdlib 4.3) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.3) gen_server.erl:814: :gen_server.init_it/6
            (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
